package dotterbear.service.eureka.scheduler.entity;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "eurekaScheduler")
public class EurekaScheduler {

  @DynamoDBHashKey(attributeName = "Id")
  private String id;

  @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
  private Date createDate;

  @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
  private Date lastUpdateDate;

  private List<String> taskList;

  private Map<String, TaskMap> taskMap;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public Date getLastUpdateDate() {
    return lastUpdateDate;
  }

  public void setLastUpdateDate(Date lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
  }

  public List<String> getTaskList() {
    return taskList;
  }

  public void setTaskList(List<String> taskList) {
    this.taskList = taskList;
  }

  public Map<String, TaskMap> getTaskMap() {
    return taskMap;
  }

  public void setTaskMap(Map<String, TaskMap> taskMap) {
    this.taskMap = taskMap;
  }

  @Override
  public String toString() {
    return String.format(
        "EurakaScheduler[id=%s, createDate=%s, lastUpdateDate=%s, taskList=%s, taskMap=%s]",
        id, createDate, lastUpdateDate, taskList, taskMap);
  }
}
